<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BookManager.Core\BookManager.Core.csproj" />
		<ProjectReference Include="..\BookManager.Presenter\BookManager.Presenter.csproj" />
		<ProjectReference Include="..\BookManager.Shared\BookManager.Shared.csproj" />
		<ProjectReference Include="..\BookManager.WinForms\BookManager.WinForms.csproj" />
	</ItemGroup>
</Project>